name: new workflow
on: [push]

jobs:
  run-shell-commands:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string 
          run: echo "hello"
        - name: multiline command
          run: |
            node -v
            npm -v 