name: checkout
on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: ls -a
      - name: list files 
        run: ls -a
# some commds regards error are throwing errors so not included 