name: checkout action
on: [push]
jobs: 
  checkout-action:
    runs-on: ubuntu-latest
    steps: 
      - name: list files
        run: ls -a
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: list files after 
        run: ls -a
