name: checkout
on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: la -a
      - name: checkout
        run: |
           git init
           git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKRN }}@github.com/$GITHUB_REPOSITORY.git"
           git frtch origin
           git checkout main
      - name: list files 
        run: ls -a
