name: Expressions & Contexts
on: [push, pull_request, issues, workflow_dispatch]
jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Simple Expressions
        run: echo "${{ 1 }}"

      - name: string ecpression
        run: echo "${{ 'this is a string' }}"

      - name: Null Expression
        run: echo "${{ null }}"

      - name: Boolean Expression
        run: echo "${{ true }}"

      - name: Comparison Expression
        run: echo "${{ 1 > 2 }}"

      - name: Equality Expression
        run: echo "${{ 'string' == 'String' }}"

      - name: And Expression
        run: echo "${{ true && false }}"

      - name: Or Expression
        run: echo "${{ true || (false && true) }}"

      - name: Dump Contexts
        run: |
          echo "${{ toJson(github) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(secrets) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          
      #     echo "${{ 'this is a string' }}"
      #     echo "${{ null }}"
      #     echo "${{ true }}"
      #     echo "${{ 1 > 2 }}"
      #     echo "${{ 'string'  == 'String' }}"
      #     echo "${{ true && false }}"
      #     echo "${{ true || (false && true) }}"
      # - name: Dump Contexts
      #   run: |
      #     echo "${{ toJson(github) }}"
      #     echo "${{ toJson(job) }}"
      #     echo "${{ toJson(secrets) }}"
      #     echo "${{ toJson(steps) }}"
      #     echo "${{ toJson(runner) }}"
