name: Expressions & Contexts
on: [push, pull_request, issues, workflow_dispatch]
jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: !
          echo ${{ 1 }}
          echo ${{ 'this is a string' }}
      - name: Dump Contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          
