name: checkout action
on: [push]
jobs: 
  checkout-action:
    runs-on: ubuntu-latest
    steps: 
      - name: list files
        run: ls -a
      - uses: action/version@v3
      - name: list files after 
        run: ls -a
