name: working dirs & shells
on: [push]
defaults:
  run:
    shell: bash
jobs: 
  display-wd-info: 
    runs-on: ununtu-latest
    steps:
      - name: display working dir and list of files
        run: 
          pwd
          ls -a
          echo $GTIHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: display working dir and list of files
        run: |
          Get-Location
          dir
          echo $env:GTIHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name: python shell
        run: |
          import platform
          print(platform.proccessor(())
